import {useState} from "react";
import {Link,useNavigate} from "react-router-dom";
import {ArrowRight} from "lucide-react";
import api from "../api";
import {useAuth} from "../context/AuthContext";
import "./Auth.css";
export default function Register(){
 const [provider,setProvider]=useState(false),[form,setForm]=useState({name:"",email:"",phone:"",password:"",providerName:"",address:"",city:""}),[error,setError]=useState(""),[loading,setLoading]=useState(false);const {login}=useAuth(),nav=useNavigate();
 const set=(k,v)=>setForm(f=>({...f,[k]:v}));
 const submit=async e=>{e.preventDefault();setLoading(true);try{await api.post("/register",{...form,role:provider?"PROVIDER":"CUSTOMER"});const u=await login();nav(u?.role==="PROVIDER"?"/provider":"/request")}catch(e){setError(e.response?.data?.msg||"Could not create account.")}finally{setLoading(false)}};
 return <main className="auth-page"><div className="auth-card wide"><p className="eyebrow">Join the network</p><h1>{provider?"Create a provider account.":"Create your account."}</h1><button type="button" className={`role-switch ${provider?"active":""}`} onClick={()=>setProvider(!provider)}>{provider?"I'm registering a service provider":"I'm a service provider"}</button><form className="form" onSubmit={submit}><div className="two"><div className="field"><label>Name</label><input value={form.name} onChange={e=>set("name",e.target.value)} required/></div><div className="field"><label>Phone</label><input value={form.phone} onChange={e=>set("phone",e.target.value)} required/></div></div><div className="field"><label>Email</label><input type="email" value={form.email} onChange={e=>set("email",e.target.value)} required/></div><div className="field"><label>Password</label><input type="password" value={form.password} onChange={e=>set("password",e.target.value)} required minLength={6}/></div>{provider&&<><div className="field"><label>Provider name</label><input value={form.providerName} onChange={e=>set("providerName",e.target.value)} required/></div><div className="two"><div className="field"><label>Address</label><input value={form.address} onChange={e=>set("address",e.target.value)} required/></div><div className="field"><label>City</label><input value={form.city} onChange={e=>set("city",e.target.value)} required/></div></div></>}{error&&<p className="error">{error}</p>}<button className="btn terracotta" disabled={loading}>{loading?<span className="spinner"/>:<>Create account <ArrowRight size={14}/></>}</button></form><p className="auth-foot">Already registered? <Link to="/login">Sign in</Link></p></div></main>
}
